// example/demo-react/src/components/MarkerDemo.tsx
import React, { useCallback, useEffect, useState } from "react";
import { SpecMarker, SpecPopup } from "@mapbox-start/react-bridge";
import { CheckControl } from "../MapDemo";

const MarkerDefault = () => <SpecMarker original lngLat={[2, 0]} />;

const MarkerCustom = () => (
  <SpecMarker lngLat={[0, 0]}>
    <div style={{ color: "red" }}>
      custom
      <br />
      marker
    </div>
  </SpecMarker>
);

const MarkerWithPopup = () => (
  <SpecPopup
    onOpen={() => {
      console.log("@@@@@@ popup open");
    }}
    onClose={() => {
      console.log("@@@@@@ popup closed");
    }}>
    <div style={{ color: "red" }}>popup content</div>
    <SpecMarker original lngLat={[4, 0]} color={"blue"} />
  </SpecPopup>
);

const MarkerDraggable = () => {
  const [lngLat, setLngLat] = useState<[number, number]>([6, 0]);
  return (
    <SpecMarker
      lngLat={lngLat}
      draggable={true}
      onDragEnd={(marker, e) => {
        const ll = marker.getLngLat();
        console.log("@@@@@ drag end e=", e, "lngLat=", ll);
        setLngLat([ll.lng, ll.lat]);
      }}
    />
  );
};

const MarkerAnimate = () => {
  const [lngLat, setLngLat] = useState<[number, number]>([8, 0]);

  const animateMarker = useCallback((timestamp: number) => {
    const radius = 10;
    setLngLat([Math.cos(timestamp / 1000) * radius, Math.sin(timestamp / 1000) * radius]);
    requestAnimationFrame(animateMarker);
  }, []);

  useEffect(() => {
    requestAnimationFrame(animateMarker);
  }, []);

  return <SpecMarker original lngLat={lngLat} />;
};

export const MarkerDemo = () => {
  return (
    <>
      <CheckControl name={"默认"}>
        <MarkerDefault />
      </CheckControl>
      <CheckControl name={"custom"}>
        <MarkerCustom />
      </CheckControl>
      <CheckControl name={"with popup"}>
        <MarkerWithPopup />
      </CheckControl>
      <CheckControl name={"draggable"}>
        <MarkerDraggable />
      </CheckControl>
      <CheckControl name={"animate"} defaultCheck={false}>
        <MarkerAnimate />
      </CheckControl>
    </>
  );
};

// example/demo-vue/src/components/MarkerDemo.vue
<template>
  <div>
    <CheckControl name="默认">
      <SpecMarker :original="true" :lngLat="[2, 0]" />
    </CheckControl>
    <CheckControl name="custom">
      <SpecMarker :lngLat="[0, 0]">
        <div style="color: red">custom<br />marker</div>
      </SpecMarker>
    </CheckControl>
    <CheckControl name="with popup">
      <SpecPopup>
        <div style="color: red">popup content</div>
        <SpecMarker :original="true" :lngLat="[4, 0]" color="blue" />
      </SpecPopup>
    </CheckControl>
    <CheckControl name="draggable">
      <SpecMarker :original="true" :lngLat="lngLat" :draggable="true" :onDragEnd="handleDrag" />
    </CheckControl>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import CheckControl from "../CheckControl.vue";
import { SpecMarker, SpecPopup } from "@mapbox-start/vue-bridge";
import { Marker, MapboxEvent } from "mapbox-gl";
@Component({
  components: { CheckControl, SpecMarker, SpecPopup },
})
export default class MarkerDemo extends Vue {
  lngLat: [number, number] = [6, 0];

  handleDrag(marker: Marker, e: MapboxEvent) {
    const ll = marker.getLngLat();
    console.log("@@@@@ drag end e=", e, "lngLat=", ll);
    this.lngLat = [ll.lng, ll.lat];
  }
}
</script>
