// example/demo-vue/src/components/ApiDemo.vue
<template>
  <div>
    <CheckControl name="flyTo" :default-check="false" :on-change="onFlyToChange" />
    <CheckControl name="fitBounds" :default-check="false" :on-change="onFitBoundsChange" />
  </div>
</template>

<script lang="ts">
import { Vue, Component, Inject } from "vue-property-decorator";
import CheckControl from "../CheckControl.vue";
import { Map } from "mapbox-gl";
@Component({
  components: { CheckControl },
})
export default class ApiDemo extends Vue {
  @Inject() map!: Map;

  onFlyToChange(state: boolean) {
    if (state) {
      this.map.flyTo({ center: [-87.61694, 41.86625], zoom: 10 });
    } else {
      this.map.flyTo({ center: [0, 0], zoom: 3 });
    }
  }

  onFitBoundsChange(state: boolean) {
    if (state) {
      this.map.fitBounds([
        [32.958984, -5.353521],
        [43.50585, 5.615985],
      ]);
    } else {
      this.map.flyTo({ center: [0, 0], zoom: 3 });
    }
  }
}
</script>

// example/demo-react/src/components/ApiDemo.tsx
import { backHome, CheckControl } from "../MapDemo";
import React from "react";
import { useMap } from "@mapbox-start/react-bridge";

const ApiFlyTo = () => {
  const map = useMap();
  return (
    <CheckControl
      name={"flyTo"}
      defaultCheck={false}
      onChange={(state) => {
        if (state) {
          map.flyTo({ center: [-87.61694, 41.86625], zoom: 10 });
        } else {
          backHome(map);
        }
      }}
    />
  );
};

const ApiFitBounds = () => {
  const map = useMap();
  return (
    <CheckControl
      defaultCheck={false}
      name={"fitBounds"}
      onChange={(state) => {
        if (state) {
          map.fitBounds([
            [32.958984, -5.353521],
            [43.50585, 5.615985],
          ]);
        } else {
          backHome(map);
        }
      }}
    />
  );
};

export const ApiDemo = () => {
  return (
    <>
      <ApiFlyTo />
      <ApiFitBounds />
    </>
  );
};
